package controller;


import DAO.UsuarioDAO;
import commons.Console;
import commons.Validadores;
import entities.Usuario;
import java.util.Arrays;
import java.sql.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelEmail = new javax.swing.JLabel();
        TFEmail = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        botaoSalvar = new javax.swing.JButton();
        labelRepetirSenha = new javax.swing.JLabel();
        password2 = new javax.swing.JPasswordField();
        labelNomeCompleto = new javax.swing.JLabel();
        TFnomeCompleto = new javax.swing.JTextField();
        labelNomeUsuario = new javax.swing.JLabel();
        TFnomeUsuario = new javax.swing.JTextField();
        labelDataNascimento = new javax.swing.JLabel();
        JFTdataNascimento = new javax.swing.JFormattedTextField();
        botaoVoltar = new javax.swing.JButton();
        labelNomeUsuario1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 41, 54));

        labelEmail.setBackground(new java.awt.Color(255, 255, 255));
        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(246, 190, 0));
        labelEmail.setText("Email");

        TFEmail.setBackground(new java.awt.Color(42, 42, 54));
        TFEmail.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        TFEmail.setForeground(new java.awt.Color(204, 204, 204));
        TFEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmailActionPerformed(evt);
            }
        });

        labelSenha.setBackground(new java.awt.Color(255, 255, 255));
        labelSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(246, 190, 0));
        labelSenha.setText("Senha");

        password.setBackground(new java.awt.Color(41, 41, 54));
        password.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        botaoSalvar.setBackground(new java.awt.Color(246, 190, 0));
        botaoSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSalvar.setForeground(new java.awt.Color(41, 41, 54));
        botaoSalvar.setText("Salvar");
        botaoSalvar.setToolTipText("");
        botaoSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        labelRepetirSenha.setBackground(new java.awt.Color(255, 255, 255));
        labelRepetirSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelRepetirSenha.setForeground(new java.awt.Color(246, 190, 0));
        labelRepetirSenha.setText("Repetir Senha");

        password2.setBackground(new java.awt.Color(41, 41, 54));
        password2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        password2.setForeground(new java.awt.Color(255, 255, 255));
        password2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password2ActionPerformed(evt);
            }
        });

        labelNomeCompleto.setBackground(new java.awt.Color(255, 255, 255));
        labelNomeCompleto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNomeCompleto.setForeground(new java.awt.Color(246, 190, 0));
        labelNomeCompleto.setText("Nome Completo");

        TFnomeCompleto.setBackground(new java.awt.Color(42, 42, 54));
        TFnomeCompleto.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        TFnomeCompleto.setForeground(new java.awt.Color(204, 204, 204));
        TFnomeCompleto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TFnomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnomeCompletoActionPerformed(evt);
            }
        });

        labelNomeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        labelNomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNomeUsuario.setForeground(new java.awt.Color(246, 190, 0));
        labelNomeUsuario.setText("Nome de Usuário");

        TFnomeUsuario.setBackground(new java.awt.Color(42, 42, 54));
        TFnomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        TFnomeUsuario.setForeground(new java.awt.Color(204, 204, 204));
        TFnomeUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TFnomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnomeUsuarioActionPerformed(evt);
            }
        });

        labelDataNascimento.setBackground(new java.awt.Color(255, 255, 255));
        labelDataNascimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDataNascimento.setForeground(new java.awt.Color(246, 190, 0));
        labelDataNascimento.setText("Data de Nascimento");

        JFTdataNascimento.setBackground(new java.awt.Color(41, 41, 54));
        JFTdataNascimento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JFTdataNascimento.setForeground(new java.awt.Color(204, 204, 204));
        try {
            JFTdataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFTdataNascimento.setPreferredSize(new java.awt.Dimension(37, 19));

        botaoVoltar.setBackground(new java.awt.Color(246, 190, 0));
        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(41, 41, 54));
        botaoVoltar.setText("Voltar");
        botaoVoltar.setToolTipText("");
        botaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        labelNomeUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        labelNomeUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNomeUsuario1.setForeground(new java.awt.Color(246, 190, 0));
        labelNomeUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomeUsuario1.setText("Cadastro");
        labelNomeUsuario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JFTdataNascimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TFnomeUsuario)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelNomeCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TFnomeCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(botaoSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(password2)
                                        .addComponent(labelRepetirSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(password)
                                        .addComponent(labelSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                                    .addComponent(TFEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelNomeUsuario1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelNomeUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(labelNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFnomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNomeCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFnomeCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRepetirSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(password2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(JFTdataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEmailActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password2ActionPerformed

    private void TFnomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnomeCompletoActionPerformed

    private void TFnomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnomeUsuarioActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
       if (!validaTela()) {
            return;
        }
       
       String nomeUsuario = TFnomeUsuario.getText();
       String nomeCompleto = TFnomeCompleto.getText();
       String senha = String.valueOf(password.getPassword());
       String email = TFEmail.getText();
       Date dataNascimento = Console.toSQLDate(JFTdataNascimento.getText());
       
       Usuario novoUsuario = new Usuario(nomeUsuario, nomeCompleto, senha, email, dataNascimento);
       
       UsuarioDAO usuarioDAO = new UsuarioDAO();
       usuarioDAO.adicionaUsuario(novoUsuario);
       
       JOptionPane.showMessageDialog(this, "Usuário cadastrado.", "Cadastro", JOptionPane.PLAIN_MESSAGE);
       
       this.setVisible(false);
       Entrar next = new Entrar();
       next.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.setVisible(false);
        Entrar next = new Entrar();
        next.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }
    
    private boolean validaTela(){
        
        if(!Validadores.validaEmail(TFnomeUsuario.getText())){
            JOptionPane.showMessageDialog(this, "Informe um nome de usuário válido.", "Validação", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        if(!Validadores.validaNome(TFnomeCompleto.getText())){
            JOptionPane.showMessageDialog(this, "Informe um nome válido.", "Validação", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        if (!Validadores.validaEmail(TFEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Informe um email válido.", "Validação", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        if(Arrays.equals(password.getPassword(), password2.getPassword()) == false || 
                password.getPassword().length == 0){
            JOptionPane.showMessageDialog(this, "Verifique se as senhas são correspondentes e preenchidas.", "Validação", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        if(!Validadores.validaData(JFTdataNascimento.getText())){
            JOptionPane.showMessageDialog(this, "Informe a data no formato DD/MM/YYYY.", "Validação", JOptionPane.INFORMATION_MESSAGE);
            return false;
            
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField JFTdataNascimento;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFnomeCompleto;
    private javax.swing.JTextField TFnomeUsuario;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDataNascimento;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNomeCompleto;
    private javax.swing.JLabel labelNomeUsuario;
    private javax.swing.JLabel labelNomeUsuario1;
    private javax.swing.JLabel labelRepetirSenha;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password2;
    // End of variables declaration//GEN-END:variables
}
