package controller;


import DAO.DoramaDAO;
import DAO.ForumDAO;
import DAO.UsuarioDAO;
import entities.Dorama;
import entities.Forum;
import entities.Sessao;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Aluno
 */
public class Menu extends javax.swing.JFrame {

    private Dorama doramaSelecionado;
    private ArrayList<Dorama> listaDoramas;
    private ArrayList<Forum> listaComentarios;

    public Menu() throws SQLException {
        initComponents();
        setLocationRelativeTo(this);
        scaleImage();
        atualizaTabela();
        listDoramas.setSelectedIndex(0);
        atualizaInfos();
        setIcon();

        UsuarioDAO usuarioDAO = new UsuarioDAO();
        Sessao.setUsuario(usuarioDAO.selecionaUsuario(Sessao.getEmail()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        capa = new javax.swing.JLabel();
        Sair = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listDoramas = new javax.swing.JList<>();
        labelTitulo = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listComentarios = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        novoComentario = new javax.swing.JTextPane();
        botaoEnviar = new javax.swing.JButton();
        labelStar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(42, 42, 54));
        jPanel1.setEnabled(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 550));

        jPanel2.setBackground(new java.awt.Color(41, 41, 54));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 190, 0));
        jLabel1.setText("Doramas");

        capa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        capa.setFocusable(false);
        capa.setInheritsPopupMenu(false);
        capa.setPreferredSize(new java.awt.Dimension(180, 260));

        Sair.setBackground(new java.awt.Color(255, 0, 0));
        Sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sair.setForeground(new java.awt.Color(255, 255, 255));
        Sair.setText("Sair");
        Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        listDoramas.setBackground(new java.awt.Color(41, 41, 54));
        listDoramas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listDoramas.setForeground(new java.awt.Color(255, 255, 255));
        listDoramas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDoramas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDoramas.setSelectionBackground(new java.awt.Color(204, 204, 0));
        listDoramas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDoramasMouseClicked(evt);
            }
        });
        listDoramas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listDoramasValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listDoramas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(capa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Sair)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(capa, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(246, 190, 0));
        labelTitulo.setText("Doramas");

        labelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        labelDescricao.setForeground(new java.awt.Color(226, 226, 226));
        labelDescricao.setText("Resumo");
        labelDescricao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelDescricao.setAutoscrolls(true);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(246, 190, 0));
        jLabel4.setText("Comentários");

        listComentarios.setBackground(new java.awt.Color(41, 41, 54));
        listComentarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listComentarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listComentarios.setEnabled(false);
        listComentarios.setRequestFocusEnabled(false);
        listComentarios.setSelectionBackground(new java.awt.Color(204, 204, 0));
        listComentarios.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(listComentarios);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(246, 190, 0));
        jLabel5.setText("Novo Comentário");

        novoComentario.setBackground(new java.awt.Color(255, 255, 255));
        novoComentario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        novoComentario.setForeground(new java.awt.Color(41, 41, 54));
        novoComentario.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        novoComentario.setSelectionColor(new java.awt.Color(41, 41, 54));
        jScrollPane2.setViewportView(novoComentario);

        botaoEnviar.setBackground(new java.awt.Color(246, 190, 0));
        botaoEnviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoEnviar.setForeground(new java.awt.Color(41, 41, 54));
        botaoEnviar.setText("Enviar");
        botaoEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEnviarMouseClicked(evt);
            }
        });
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });

        labelStar.setText("Stars");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoEnviar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(labelStar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)
                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTitulo)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(labelStar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SairMouseClicked

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        boolean sair = caixaConfirmacao("Sair");
        if (sair)
            System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void listDoramasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDoramasMouseClicked

    }//GEN-LAST:event_listDoramasMouseClicked

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        boolean enviar = caixaConfirmacao("Enviar Comentário");
        if (enviar) {

            if (novoComentario.getText().isBlank() || novoComentario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por gentileza, insira um comentário válido.", "Comentário", JOptionPane.INFORMATION_MESSAGE);
            } else {
                ForumDAO forumDAO = new ForumDAO();
                Forum novoForum = new Forum(doramaSelecionado.getIdDorama(), Sessao.getUsuario().getIdUsuario(), novoComentario.getText());

                forumDAO.adicionaComentario(novoForum);

            }
            novoComentario.setText("");
            try {
                atualizaInfos();
            } catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botaoEnviarActionPerformed

    private void botaoEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEnviarMouseClicked

    }//GEN-LAST:event_botaoEnviarMouseClicked

    private void listDoramasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listDoramasValueChanged
        try {
            atualizaInfos();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_listDoramasValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void scaleImage() {
        ImageIcon icon = new ImageIcon("C:\\Users\\Aluno\\OneDrive - EDU - Organização Educacional Barão de Mauá\\Facul\\6º Sem\\Padrões e Paradigmas de Programação\\Kleob\\Kleob\src\\logo\\kleobpngredondo.png");
        //scaling image to fit in jlable
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        logo.setIcon(scaledIcon);
    }
    
    public void alteraEstrela(Float nota) {
        String caminho = "C:\\Users\\Aluno\\OneDrive - EDU - Organização Educacional Barão de Mauá\\Facul\\6º Sem\\Padrões e Paradigmas de Programação\\Kleob\\Kleob\src\\Stars\\";
        String notaImagem;
        
        if(nota <=0.24)
            notaImagem = "star0.png";
        else if (nota > 0.24 && nota <= 0.74)
            notaImagem = "star05.png";
        else if (nota >0.74 && nota <= 1.24)
            notaImagem = "star1.png";
        else if (nota >1.24 && nota <= 1.74)
            notaImagem = "star15.png";
        else if (nota >1.74 && nota <= 2.24)
            notaImagem = "star2.png";
        else if (nota >2.24 && nota <= 2.74)
            notaImagem = "star25.png";
        else if (nota >2.74 && nota <= 3.24)
            notaImagem = "star3.png";
        else if (nota >3.24 && nota <= 3.74)
            notaImagem = "star35.png";
        else if (nota >3.74 && nota <= 4.24)
            notaImagem = "star4.png";
        else if (nota >4.24 && nota <= 4.74)
            notaImagem = "star45.png";
        else
            notaImagem = "star5.png";
        
         ImageIcon icon = new ImageIcon(caminho+notaImagem);
         
        Image imagem = icon.getImage();
        Image imgScale = imagem.getScaledInstance(labelStar.getWidth(), labelStar.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        labelStar.setIcon(scaledIcon);
    }


    private void atualizaTabela() throws SQLException {
        DoramaDAO doramaDAO = new DoramaDAO();

        listaDoramas = doramaDAO.localizarDorama();

        //PARA LISTA
        DefaultListModel<String> modelo = new DefaultListModel<>();
        listDoramas.setModel(modelo);
        //
        listDoramas.removeAll();

        if (listaDoramas.isEmpty()) {
            return;
        }

        for (int i = 0; i < listaDoramas.size(); i++) {
            modelo.addElement(listaDoramas.get(i).getTitulo());
        }

    }

    private void atualizaInfos() throws SQLException {
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yy");

        Integer selecionado = listDoramas.getSelectedIndex(); //retorna int
        doramaSelecionado = listaDoramas.get(selecionado);

        String stringIcon;

        if (doramaSelecionado.getImagem() == null) {
            stringIcon = "C:\\Users\\Aluno\\OneDrive - EDU - Organização Educacional Barão de Mauá\\Facul\\6º Sem\\Padrões e Paradigmas de Programação\\Kleob\\Kleob\src\\capaDorama\\default.jpg";
        } else {
            stringIcon = "C:\\Users\\Aluno\\OneDrive - EDU - Organização Educacional Barão de Mauá\\Facul\\6º Sem\\Padrões e Paradigmas de Programação\\Kleob\\Kleob\src\\capaDorama\\" + doramaSelecionado.getImagem();
        }

        ImageIcon icon = new ImageIcon(stringIcon);//scaling image to fit in jlable

        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(capa.getWidth(), capa.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        capa.setIcon(scaledIcon);

        labelTitulo.setText("<html>" +doramaSelecionado.getTitulo() + " | Eps: " + doramaSelecionado.getEpisodio() + " | " + doramaSelecionado.getGenero()+ "</html>");
        labelDescricao.setText("<html>" + doramaSelecionado.getDescricao() + "</html>");

        ForumDAO forumDAO = new ForumDAO();
        listaComentarios = forumDAO.localizarForum(doramaSelecionado.getIdDorama());

        DefaultListModel<String> modeloComent = new DefaultListModel<>();
        listComentarios.setModel(modeloComent);

        listComentarios.removeAll();
        
        alteraEstrela(doramaSelecionado.getNota());

        for (int i = 0; i < listaComentarios.size(); i++) {
            modeloComent.addElement("<html>" + listaComentarios.get(i).getNomeUsuario()
                    + "-" + format.format(listaComentarios.get(i).getDataComent())
                    + "-" + listaComentarios.get(i).getComentario() + "</html>");
        }

    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("kleobpngredondo.png")));
    }

    private boolean caixaConfirmacao(String acaoConfirmar) {

        int resposta = JOptionPane.showConfirmDialog(this, "Deseja confirmar essa ação? ", acaoConfirmar.toUpperCase(), JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            return true;
        } else {
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair;
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JLabel capa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelStar;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JList<String> listComentarios;
    private javax.swing.JList<String> listDoramas;
    private javax.swing.JLabel logo;
    private javax.swing.JTextPane novoComentario;
    // End of variables declaration//GEN-END:variables
}
